# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

accountants = Category.create(name: 'Accountants')
art = Category.create(name: 'Art Galleries/Antiques')
attorneys = Category.create(name: 'Attorneys')
automobile = Category.create(name: 'Automobile Services')
banks = Category.create(name: 'Banks')
biotech = Category.create(name: 'Biotechnology/Life Sciences')
business = Category.create(name: 'Business Services')
technology = Category.create(name: 'Computer Technology & Web Design')
construction = Category.create(name: 'Construction & Architects')
dentist = Category.create(name: 'Dentist')
financial = Category.create(name: 'Financial Services')
florist = Category.create(name: 'Florist, Garden & Landscape')
graphic = Category.create(name: 'Graphic Arts')
historical = Category.create(name: 'Historical Points of Interest')
household = Category.create(name: 'Household Services')
insurance = Category.create(name: 'Insurance')
learning = Category.create(name: 'Learning, Academic & Arts')
government = Category.create(name: 'Local Government & Civic Officials')
lodging = Category.create(name: 'Lodging')
medical = Category.create(name: 'Medical Care Services')
multimedia = Category.create(name: 'Multimedia')
music = Category.create(name: 'Music')
newspaper = Category.create(name: 'Newspaper & Publications')
nonprofit = Category.create(name: 'Non-Profit')
wellness_beauty = Category.create(name: 'Personal Wellness & Beauty')
pharmacy = Category.create(name: 'Pharmacy')
photography = Category.create(name: 'Photography/Photo Supplies & Framing')
promotional = Category.create(name: 'Promotional Products & Corporate Gifts')
real_estate = Category.create(name: 'Real Estate')
recreation = Category.create(name: 'Recreation & Fitness')
restaurant = Category.create(name: 'Restaurant, Bakery, Café & Catering')
retail = Category.create(name: 'Retail Shopping')
retirement = Category.create(name: 'Retirement Community/Assisted Living')
transportation = Category.create(name: 'Transportation')
travel = Category.create(name: 'Travel & Tourism')

Business.create(name: "A Pocketful of Posies", address: "1656 Massachusetts Ave.", phone: "(781) 460-8587", website: "http://www.apocketfulofposies.com", category_id: retail.id)
Business.create(name: "Abbott and Company LLC", address: "10 Muzzey St.", phone: "(781) 863-2272", fax: "(781) 863-2274", website: "http://www.abbottandcompany.net", category_id: accountants.id)
Business.create(name: "Accelerated Fitness", address: "153 North St.", phone: "(781) 538-6664", website: "http://www.acceleratedfts.com", category_id: recreation.id)
Business.create(name: "Alan Bogosian Electric Inc.", address: "640 Lowell St.", phone: "(781) 863-5900", fax: "(781) 862-0475", category_id: construction.id)
Business.create(name: "Alexander’s Pizza", address: "180 Bedford St.", phone: "(781) 862-3312", fax: "(781) 863-1980", website: "http://www.alexanderspizza.net", category_id: restaurant.id)
Business.create(name: "Aloft Hotel Lexington", address: "727 Marrett Rd.", phone: "(781) 761-1700", website: "http://www.aloftlexington.com", category_id: lodging.id)
Business.create(name: "Arlex Oil Corporation", address: "275 Massachusetts Ave.", phone: "(781) 862-3400", website: "http://www.arlexenergy.com", category_id: household.id)
Business.create(name: "Avalon at Lexington Hills", address: "1000 Main Campus Dr.", phone: "(781) 860-8851", fax: "(781) 860-8858", website: "http://www.avalonatlexingtonhills.com", category_id: real_estate.id)
Business.create(name: "Avenue Deli", address: "1806 Massachusetts Ave.", phone: "(781) 862-1806", website: "http://www.avenuedelicatering.com", category_id: restaurant.id)
Business.create(name: "Bella Sante", address: "76 Bedford St.", phone: "(617) 424-9930", website: "http://www.bellasante.com", category_id: wellness_beauty.id)
Business.create(name: "Berman’s Wine & Spirits", address: "55 Massachusetts Ave.", phone: "(781) 862-0515", fax: "(781) 862-7088", website: "http://www.bermansfinewines.com", category_id: retail.id)
Business.create(name: "Bertucci’s Brick Oven Pizzeria", address: "1777 Massachusetts Ave.", phone: "(781) 860-9000", fax: "(781) 862-5907", website: "http://www.bertuccis.com", category_id: restaurant.id)
Business.create(name: "Beth Israel Deaconess HealthCare", address: "482 Bedford St.", phone: "(781) 528-2400", fax: "(781) 528-2474", website: "http://www.bidmc.org/lexington", category_id: medical.id)
Business.create(name: "Bickling Financial Services, Inc.", address: "35 Bedford St.", phone: "(781) 862-9792", fax: "(781) 674-2545", website: "http://www.bickling.com", category_id: financial.id)
Business.create(name: "Bina Farm Center", address: "55 Allen St.", phone: "(508) 651-2462", fax: "(508) 651-2463", website: "http://www.binafarm.org", category_id: nonprofit.id)
Business.create(name: "Blinds With Vision", address: "356 Marrett Rd.", phone: "(781) 402-0123", website: "http://www.blindswithvision.com", category_id: retail.id)
Business.create(name: "Boston Sports Club", address: "475 Bedford St.", phone: "(781) 861-8600", website: "http://www.mysportsclubs.com", category_id: recreation.id)
Business.create(name: "Thomas G. Braun, D.D.S.", address: "20 Muzzey St.", phone: "(781) 862-2790", fax: "(781) 862-6503", website: "http://www.thomasbraundentist.com", category_id: dentist.id)
Business.create(name: "Brookhaven at Lexington", address: "1010 Waltham St.", phone: "(781) 863-9660", fax: "(781) 863-9944", website: "http://www.brookhavenatlexington.org", category_id: retirement.id)
Business.create(name: "Brookline Bank", address: "1793 Massachusetts Ave.", phone: "(781) 863-2820", fax: "(781) 863-5148", website: "http://www.brooklinebank.com", category_id: banks.id)
Business.create(name: "C&W Transportation", address: "240 Bedford St.", phone: "(781) 862-4747", category_id: transportation.id)
Business.create(name: "Cambridge Savings Bank", address: "1781 Massachusetts Ave.", phone: "(617) 441-4234", fax: "(781) 861-8962", website: "http://www.cambridgesavings.com", category_id: banks.id)
Business.create(name: "Cambridge Trust Company", address: "1690 Massachusetts Ave.", phone: "(781) 863-0976", fax: "(781) 372-1090", website: "http://www.cambridgetrust.com", category_id: banks.id)
Business.create(name: "CareWell Urgent Care", address: "58 Bedford St.", phone: "(781) 538-4526", fax: "(781) 538-4531", website: "http://www.carewellurgentcare.com", category_id: medical.id)
Business.create(name: "Catch A Falling Star", address: "7 Depot Sq.", phone: "(781) 674-2432", fax: "(781) 674-2619", website: "http://www.catchafallingstartoys.com", category_id: retail.id)
Business.create(name: "Children’s Center of Lexington", address: "1580 Massachusetts Ave.", phone: "(781) 861-9370", fax: "(781) 851-5071", website: "http://www.cclex.org", category_id: medical.id)
Business.create(name: "Colin Smith Architecture, Inc.", address: "1666 Massachusetts Ave.", phone: "(781) 274-0955", website: "http://www.colinsmitharch.com", category_id: construction.id)
Business.create(name: "Colonial Times Magazine", address: "805 Massachusetts Ave.", phone: "(781) 274-9997", fax: "(781) 652-0215", website: "http://www.colonialtimesmagazine.com", category_id: newspaper.id)
Business.create(name: "Complex IT, LLC", address: "9 Meriam St.", phone: "(781) 879-0075", website: "http://www.complexitllc.com", category_id: technology.id)
Business.create(name: "Cotting School", address: "453 Concord Ave.", phone: "(781) 862-7323", fax: "(781) 402-0233", website: "http://www.cotting.org", category_id: learning.id)
Business.create(name: "Crafty Yankee, Inc.", address: "1838 Massachusetts Ave.", phone: "(781) 863-1219", fax: "(781) 861-7550", website: "http://www.craftyyankee.com", category_id: retail.id)
Business.create(name: "Crickets Flowers", address: "229 Massachusetts Ave.", phone: "(781) 861-1030", fax: "(781) 862-8640", website: "http://www.cricketsflorist.com", category_id: florist.id)
Business.create(name: "Cubist Pharmaceuticals, Inc.", address: "65 Hayden Ave.", phone: "(781) 860-8660", fax: "(781) 861-0566", website: "http://www.cubist.com", category_id: biotech.id)
Business.create(name: "Dr Barry J Cunha & Dr Nabil R Ibrahim DDS PC", address: "35 Bedford St., Ste. 16", phone: "(781) 863-0096", fax: "(781) 863-5374", website: "http://www.cunhaibrahimddspc.com", category_id: dentist.id)
Business.create(name: "Dance Inn", address: "1403 Massachusetts Ave.", phone: "(781) 863-5360", fax: "(781) 861-2981", website: "http://www.thedanceinn.com", category_id: learning.id)
Business.create(name: "David M. Santo General Contracting", address: "6 Utica Street", phone: "(781) 861-8425", category_id: construction.id)
Business.create(name: "Digital Federal Credit Union", address: "1751 Massachusetts Ave.", phone: "(781) 402-0920", website: "http://www.dcu.org", category_id: banks.id)
Business.create(name: "Dreamline Modular Homes, LLC", address: "403 Waltham St.", phone: "(781) 862-8453", fax: "(781) 862-8454", website: "http://www.dreamlinemodular.com", category_id: construction.id)
Business.create(name: "Duffy Properties", address: "411 Waverly Oaks Rd.", phone: "(781) 647-5775", website: "http://www.duffyproperties.com", category_id: real_estate.id)
Business.create(name: "Eagle Bank", address: "1768 Massachusetts Ave.", phone: "(781) 862-3790", website: "http://www.eaglebank.com", category_id: banks.id)
Business.create(name: "Eastern Bank", address: "1833 Mass Ave", phone: "(781) 274-9774", website: "http://www.easternbank.com", category_id: banks.id)
Business.create(name: "Edward Jones Financial Advisor", address: "442 Marrett Rd.", phone: "(781) 860-8809", fax: "(877) 726-4440", website: "http://www.edwardjones.com", category_id: financial.id)
Business.create(name: "Element Hotel Lexington", address: "727 Marrett Rd.", phone: "(781) 761-1755", website: "http://www.elementlexington.com", category_id: lodging.id)
Business.create(name: "Elite Freestyle Karate", address: "1304 Massachusetts Ave.", phone: "(781) 942-9898", fax: "(781) 942-9899", website: "http://www.elitefreestylekarate.com", category_id: recreation.id)
Business.create(name: "Empow Studios", address: "1776 Massachusetts Ave.", phone: "(617) 395-7527", fax: "(617) 812-0233", website: "http://www.empow.me", category_id: recreation.id)
Business.create(name: "Encharter Insurance LLC", address: "1666 Massachusetts Ave.", phone: "(413) 658-3431", fax: "(800) 754-1602", website: "http://www.encharter.com", category_id: insurance.id)
Business.create(name: "Eye Look Optical", address: "1760 Massachusetts Ave.", phone: "(781) 862-4510", fax: "(781) 674-0366", website: "http://www.eyelookoptical.net", category_id: retail.id)
Business.create(name: "Falk Marques Group", address: "9 Meriam St.", phone: "(617) 283-6282", website: "http://www.falkmarquesgroup.com", category_id: business.id)
Business.create(name: "The Family Album", address: "274 Marrett Rd.", phone: "(781) 652-0167", website: "http://www.familyallbumphoto.com", category_id: photography.id)
Business.create(name: "Fancy Flea Antiques", address: "1841 Massachusetts Ave.", phone: "(781) 862-9650", fax: "(781) 862-9650", website: "http://www.fancyfleaantiques.com", category_id: art.id)
Business.create(name: "Fargo Street Associates, Inc.", address: "90A Hancock St.", phone: "(781) 888-8228", category_id: real_estate.id)
Business.create(name: "Feinmann, Inc.", address: "27 Muzzey St.", phone: "(781) 860-9800", fax: "(781) 860-7800", website: "http://www.feinmann.com", category_id: construction.id)
Business.create(name: "Law Office of Thomas O. Fenn, Esq.", address: "9 Meriam St., Ste. 23", phone: "(781) 862-4181", fax: "(781) 862-1302", website: "http://www.lexingtonlawyer.com", category_id: attorneys.id)
Business.create(name: "Fitness Together", address: "433 Marrett Rd.", phone: "(781) 862-1175", website: "http://www.fitnesstogether.com/lexington", category_id: recreation.id)
Business.create(name: "FoxGloves Fine Gardening & Design", address: "1 Bow St.", phone: "(781) 862-6927", website: "http://www.foxglovesgardens.com", category_id: florist.id)
Business.create(name: "Get in Shape for Women", address: "442 Marrett Rd.", phone: "(781) 862-0707", website: "http://www.getinshapeforwomen.com", category_id: recreation.id)
Business.create(name: "GouldSherwood Consulting", address: "5 Militia Dr.", phone: "(718) 862-2549", website: "http://www.gouldsherwood.com", category_id: technology.id)
Business.create(name: "Grant Cole Realtors", address: "52B Waltham St.", phone: "(781) 862-3636", fax: "(781) 862-8570", website: "http://www.grantcole.com", category_id: real_estate.id)
Business.create(name: "Hair Cuttery", address: "1686 Massachusetts Ave.", phone: "(781) 861-1208", website: "http://www.haircuttery.com", category_id: wellness_beauty.id)
Business.create(name: "Hammond Residential Real Estate", address: "1775 Massachusetts Ave.", phone: "(781) 861-8100", fax: "(781) 861-7504", website: "http://www.hammondre.com", category_id: real_estate.id)
Business.create(name: "Haven", address: "1646 Massachusetts Ave.", phone: "(781) 862-0411", fax: "(781) 240-6044", website: "http://www.haven-lexington.com", category_id: retail.id)
Business.create(name: "The Higgins Group Realtors", address: "1688 Massachusetts Ave.", phone: "(781) 862-1700", fax: "(781) 862-2218", website: "http://www.higginsre.com", category_id: real_estate.id)
Business.create(name: "il Casale Lexington", address: "727 Massachusetts Ave.", phone: "(781) 538-5846", website: "http://www.ilcasalelexington.com", category_id: restaurant.id)
Business.create(name: "Incite Architecture", address: "1620 Massachusetts Ave.", phone: "(781) 862-3444", fax: "(781) 863-0722", website: "http://www.incitearchitecture.com", category_id: construction.id)
Business.create(name: "The Inn at Hastings Park / Artistry on the Green", address: "2027 Massachusetts Ave.", phone: "(781) 301-6660", website: "http://www.innathastingspark.com", category_id: lodging.id)
Business.create(name: "Ixtapa Mexican Restaurant", address: "177 Massachusetts Ave.", phone: "(781) 863-8653", fax: "(781) 863-8610", website: "http://www.ixtapacantina.com", category_id: restaurant.id)
Business.create(name: "JM Associates Consulting", address: "279 Marrett Rd.", phone: "(781) 439-3894", category_id: business.id)
Business.create(name: "Kajko, Weisman & Colasanti, LLP", address: "430 Bedford St.", phone: "(781) 860-9500", website: "http://www.massfirm.com", category_id: attorneys.id)
Business.create(name: "Kane Investments, Inc.", address: "1646 Massachusetts Ave.", phone: "(617) 680-8846", category_id: real_estate.id)
Business.create(name: "Katahdin Woods of Lexington", address: "1 Katahdin Dr.", phone: "(781) 862-1998", website: "http://www.katahdinwoodsapts.com", category_id: real_estate.id)
Business.create(name: "Katlin Travel Group", address: "1840 Massachusetts Ave.", phone: "(781) 862-6229", fax: "(781) 674-2080", website: "http://www.katlintravel.com", category_id: travel.id)
Business.create(name: "Representative Jay Kaufman", address: "1 Childs Rd.", phone: "(781) 862-6181", website: "http://www.jaykaufman.com", category_id: government.id)
Business.create(name: "Keys for Kids", address: "1050 Waltham St.", phone: "(781) 274-9729", website: "http://www.keys-for-kids.com", category_id: learning.id)
Business.create(name: "KingLu International, LLC", address: "20 Tufts Rd.", phone: "(781) 862-8583", fax: "(781) 862-8584", category_id: business.id)
Business.create(name: "Carla C. Leone, Esq.", address: "175 Bedford St.", phone: "(781) 862-3100", fax: "(781) 862-3114", website: "http://www.carlaleonelaw.com", category_id: attorneys.id)
Business.create(name: "Town Of Lexington", address: "1625 Massachusetts Ave.", phone: "(781) 862-0500", website: "http://www.lexingtonma.gov", category_id: government.id)
Business.create(name: "Lexington Ace Hardware", address: "327 Woburn St.", phone: "(781) 863-0100", category_id: retail.id)
Business.create(name: "Lexington Arts & Crafts Society, Inc", address: "130 Waltham St.", phone: "(781) 862-9696", website: "http://www.lacsma.org", category_id: learning.id)
Business.create(name: "Lexington Christian Academy", address: "48 Bartlett Ave.", phone: "(781) 862-7850", fax: "(781) 863-8503", website: "http://www.lca.edu", category_id: learning.id)
Business.create(name: "Lexington Commission on Disability", address: "37 Barberry Rd.", phone: "(781) 862-1979", category_id: government.id)
Business.create(name: "Lexington Fitness Club", address: "177 Bedford St.", phone: "(781) 862-0330", website: "http://www.lexfitclub.com", category_id: recreation.id)
Business.create(name: "Lexington Graphics Inc.", address: "76 Bedford St.", phone: "(781) 863-9510", fax: "(781) 863-1081", website: "http://www.lexgraph.com", category_id: graphic.id)
Business.create(name: "Lexington Historical Society", address: "13 Depot Sq.", phone: "(781) 862-1703", website: "http://www.lexingtonhistory.org", category_id: historical.id)
Business.create(name: "Lexington Logistics Services LLC", address: "244 Bedford St.", phone: "(781) 862-6550", website: "http://www.lexlogistics.com", category_id: business.id)
Business.create(name: "Lexington Pediatrics, P.C.", address: "19 Muzzey St.", phone: "(781) 862-4110", fax: "(781) 863-2007", website: "http://www.lexpeds.com", category_id: medical.id)
Business.create(name: "Lexington Symphony", address: "3 Wallis Court", phone: "(781) 523-9009", website: "http://www.lexingtonsymphony.org", category_id: music.id)
Business.create(name: "Lexington Therapeutic Massage", address: "9 Meriam St.", phone: "(781) 863-0482", website: "http://www.lexingtontherapeuticmassage.com", category_id: medical.id)
Business.create(name: "Lexington Violin School and Lexington Strings", address: "175 Grove St.", phone: "(781) 862-8565", fax: "(781) 862-8565", website: "http://www.lexingtonviolinschool.com", category_id: music.id)
Business.create(name: "Lexington Wealth Management", address: "12 Waltham St.", phone: "(781) 860-7745", fax: "(781) 862-4392", website: "http://www.lexingtonwealth.com", category_id: financial.id)
Business.create(name: "LexMedia", address: "1001 Main Campus Dr.", phone: "(781) 862-5388", website: "http://www.lexmedia.org", category_id: multimedia.id)
Business.create(name: "Liberty Mutual Insurance", address: "173 Bedford St.", phone: "(781) 861-8750", fax: "(781) 861-1903", website: "http://www.libertymutual.com/helenhellstrom", category_id: insurance.id)
Business.create(name: "Main Street Fundraising LLC", address: "23 Nickerson Rd.", phone: "(617) 823-5181", website: "http://www.mainstfundraising.com", category_id: promotional.id)
Business.create(name: "Margaritas Mexican Restaurant", address: "438 Bedford St.", phone: "(339) 970-2250", fax: "(339) 970-2300", website: "http://www.margs.com", category_id: restaurant.id)
Business.create(name: "Marios Italian Restaurant", address: "1733 Massachusetts Ave.", phone: "(781) 861-1182", fax: "(781) 860-9568", website: "http://www.marioslexington.com", category_id: restaurant.id)
Business.create(name: "Mass. Ave. Car Wash", address: "31 Massachusetts Ave.", phone: "(781) 275-0380", fax: "(781) 271-0180", category_id: automobile.id)
Business.create(name: "McSweeney Painting", address: "435 Lincoln St.", phone: "(617) 974-4912", fax: "(781) 860-9522", category_id: construction.id)
Business.create(name: "MiniLuxe Lexington", address: "1718 Massachusetts Ave.", phone: "(339) 970-2322", website: "http://www.miniluxe.com", category_id: wellness_beauty.id)
Business.create(name: "Minute Women Home Care", address: "238 Bedford St.", phone: "(781) 862-3300", fax: "(781) 861-7721", website: "http://www.mwhomecare.com", category_id: household.id)
Business.create(name: "Minuteman Regional Vocational Technical High School", address: "758 Marrett Rd.", phone: "(781) 861-6500", website: "http://www.minuteman.org", category_id: learning.id)
Business.create(name: "Mount Auburn Healthcare At Lexington", address: "57 Bedford St.", phone: "(781) 862-7500", fax: "(781) 861-1409", website: "http://www.mountauburnhospital.org", category_id: medical.id)
Business.create(name: "Munroe Center for the Arts", address: "1403 Massachusetts Ave.", phone: "(781) 862-6040", fax: "(781) 674-2787", website: "http://www.munroecenter.org", category_id: learning.id)
Business.create(name: "Oldenburg Architecture", address: "1666 Massachusetts Ave.", phone: "(781) 862-2275", website: "http://www.oldenarch.com", category_id: construction.id)
Business.create(name: "Otis Brown Insurance Agency", address: "1 Militia Dr.", phone: "(781) 862-7700", website: "http://www.otisbrown.com", category_id: insurance.id)
Business.create(name: "Peets Coffee & Tea, Inc.", address: "1749 Massachusetts Ave.", phone: "(781) 357-2090", fax: "(781) 357-2092", website: "http://www.peets.com", category_id: restaurant.id)
Business.create(name: "Petra Clothing for Women", address: "1844 Massachusetts Ave.", phone: "(781) 274-7000", website: "http://www.petralexington.com", category_id: retail.id)
Business.create(name: "Pine Knoll Nursing Center", address: "30 Watertown St.", phone: "(781) 862-8151", fax: "(781) 862-3703", website: "http://www.pineknollnursingcenter.com", category_id: retirement.id)
Business.create(name: "Pinot’s Palette Lexington Center", address: "7A Meriam St.", phone: "(781) 862-3200", website: "http://www.pinotspalette.com/LexingtonCenter", category_id: learning.id)
Business.create(name: "Quality Inn & Suites", address: "440 Bedford St.", phone: "(781) 861-0850", fax: "(781) 861-0821", website: "http://www.qualityinnlexington.com", category_id: lodging.id)
Business.create(name: "Rancatore’s Ice Cream, Inc.", address: "1752 Massachusetts Ave.", phone: "(781) 862-5090", fax: "(781) 861-3430", website: "http://www.rancs.com", category_id: restaurant.id)
Business.create(name: "Related Beal Ledgemont Center", address: "99 Hayden Ave.", phone: "(781) 861-7786", website: "http://www.ledgemontcenter.com", category_id: real_estate.id)
Business.create(name: "The Research Institute for Learning and Development", address: "4 Militia Dr.", phone: "(781) 861-3711", website: "http://www.ildlex.org", category_id: learning.id)
Business.create(name: "Royal India Bistro", address: "7 Meriam St.", phone: "(781) 861-7350", fax: "(781) 861-7352", website: "http://www.bistroroyalindia.com", category_id: restaurant.id)
Business.create(name: "Ruyi Restaurant", address: "27 Waltham St.", phone: "(781) 863-2800", website: "http://www.ruyilexington.com", category_id: restaurant.id)
Business.create(name: "Sartori Insurance Agency", address: "76 Bedford St.", phone: "(781) 861-6900", fax: "(781) 862-8831", website: "http://www.sartoriinsurance.com", category_id: insurance.id)
Business.create(name: "Lester Savage, Real Estate/Century21 Commonwealth", address: "9 Meriam St.", phone: "(781) 862-0202", fax: "(781) 861-0083", website: "http://www.lexingtonre.com", category_id: real_estate.id)
Business.create(name: "Scottish Rite Masonic Museum and Library", address: "33 Marrett Rd.", phone: "(781) 861-6559", fax: "(781) 861-9846", website: "http://www.nationalheritagemuseum.org", category_id: historical.id)
Business.create(name: "Seasons Four, The Outdoor Living Store", address: "1265 Massachusetts Ave.", phone: "(781) 861-1200", fax: "(781) 674-4123", website: "http://www.seasonsfour.com", category_id: florist.id)
Business.create(name: "Sekisui Diagnostics", address: "4 Hartwell Place", phone: "(781) 652-7800", fax: "(781) 652-7901", website: "http://www.sekisuidiagnostics.com", category_id: biotech.id)
Business.create(name: "Shadley Associates, P.C.", address: "1730 Massachusetts Ave.", phone: "(781) 652-8809", fax: "(781) 862-2687", website: "http://www.shadleyassociates.com", category_id: construction.id)
Business.create(name: "Shapiro Elder Law", address: "48 Waltham St.", phone: "(781) 862-7050", website: "http://www.shapiroelderlaw.com", category_id: attorneys.id)
Business.create(name: "Shemin Nurseries, Inc.", address: "1265 Massachusetts Ave.", phone: "(781) 861-1111", fax: "(781) 861-7608", website: "http://www.shemin.net", category_id: florist.id)
Business.create(name: "Shire", address: "300 Shire Way", phone: "(781) 482-2779", website: "http://www.shire.com", category_id: biotech.id)
Business.create(name: "Spectacle Management", address: "4 Muzzey St.", phone: "(617) 531-1257", fax: "(617) 531-1257", website: "http://www.spectacleshows.com", category_id: music.id)
Business.create(name: "Spectrum Music", address: "1844B Massachusetts Ave.", phone: "(781) 862-0088", fax: "(781) 861-1335", website: "http://www.spectrummusic.com", category_id: music.id)
Business.create(name: "Summer’s Edge Day Camp & Tennis School", address: "758 Marret Rd.", phone: "(781) 391-3343", website: "http://www.summersedgedaycamp.com", category_id: recreation.id)
Business.create(name: "Supportive Living, Inc.", address: "7 Oakland St.", phone: "(781) 937-3199", fax: "(781) 937-5503", website: "http://www.supportivelivinginc.org", category_id: nonprofit.id)
Business.create(name: "Tarpey Insurance Group Inc.", address: "807 Mass Ave.", phone: "(781) 861-7878", fax: "(781) 861-1109", website: "http://www.tarpeyinsurance.com", category_id: insurance.id)
Business.create(name: "Theatre Pharmacy, Inc.", address: "1784 Massachusetts Ave.", phone: "(781) 862-4480", fax: "(781) 860-9567", website: "http://www.theatrepharmacy.com", category_id: pharmacy.id)
Business.create(name: "ThinkdiffInstitute", address: "1666 Massachusetts Ave.", phone: "(888) 417-3159", fax: "(888) 417-3159", website: "http://www.think-diff.com", category_id: medical.id)
Business.create(name: "Tricon Sports, Inc", address: "415 Waltham St.", phone: "(781) 861-8921", website: "http://www.triconsportsinc.com", category_id: retail.id)
Business.create(name: "Joseph T. Twardy, Jr., CPA LLC", address: "405 Waltham St.", phone: "(781) 274-6600", website: "http://www.twardycpa.com", category_id: accountants.id)
Business.create(name: "Via Lago Cafe and Catering", address: "1845 Massachusetts Ave.", phone: "(781) 861-6174", fax: "(781) 860-0552", website: "http://www.vialagocatering.com", category_id: restaurant.id)
Business.create(name: "Vine Brook Tavern", address: "20 Waltham St.", phone: "(781) 863-2012", fax: "(781) 863-2013", website: "http://www.vinebrooktavern.com", category_id: restaurant.id)
Business.create(name: "Wagon Wheel Nursery & Farmstand", address: "927 Waltham St.", phone: "(781) 862-2112", fax: "(781) 862-6776", website: "http://www.wagonwheelfarmstand.com", category_id: florist.id)
Business.create(name: "Walden Framer", address: "121 Massachusetts Ave.", phone: "(978) 831-3351", fax: "(781) 862-6134", website: "http://www.waldenframer.com", category_id: photography.id)
Business.create(name: "Watertown Savings Bank", address: "1075 Waltham St.", phone: "(617) 928-9000", fax: "(617) 972-9218", website: "http://www.watertownsavings.com", category_id: banks.id)
Business.create(name: "Waxy OConnor’s Irish Pub & Restaurant", address: "94 Hartwell Ave.", phone: "(781) 861-9299", fax: "(781) 861-9298", website: "http://www.waxys.com", category_id: restaurant.id)
Business.create(name: "William Raveis Real Estate", address: "1713 Mass Ave.", phone: "(781) 861-9600", fax: "(781) 861-9601", website: "http://www.raveis.com", category_id: real_estate.id)
Business.create(name: "Wingate Wealth Advisors, LLC", address: "450 Bedford St.", phone: "(781) 862-7100", website: "http://www.wingatewealthadvisors.com", category_id: financial.id)
Business.create(name: "Woodhaven Realty", address: "424 Marrett Rd.", phone: "(781) 862-6232", website: "http://www.woodhavenrealty.net", category_id: real_estate.id)
Business.create(name: "Yangtze River Restaurant", address: "21 Depot Sq.", phone: "(781) 861-6030", fax: "(781) 861-0410", website: "http://www.yangtzeriverlexington.com", category_id: restaurant.id)
Business.create(name: "Youville Place Assisted Living Residence", address: "10 Pelham Rd.", phone: "(781) 861-3535", fax: "(781) 862-4289", website: "http://www.youvilleassistedliving.org", category_id: retirement.id)